(*   Title: EviL/ROOT.ML
 *   ID: $Id$
 *)

no_document use_thy "LaTeXsugar"; 
use_thy "MinAxClass";
use_thy "ClassAxClass";
(* use_thy "IntAxClass"; *)
no_document use_thy "Infinite_Set"; 
use_thy "Set_to_List";
use_thy "Little_Lindy";
use_thy "Classic";
use_thy "EviL_Semantics";
use_thy "EviL_Logic";
use_thy "EviL_Properties";
use_thy "EviL_Truth";
use_thy "Dual_EviL_Semantics";
use_thy "EviL_Columns";
(* use_thy "ModalAxClass"; *)

